In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import pylab as pl

In [4]:
data = pd.read_csv('data/HR_comma_sep.csv')
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Department', 'salary'],
      dtype='object')

In [6]:
x = data[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary']]
x.head()

satisfaction_level  average_montly_hours  promotion_last_5years  salary
0                0.38                   157                      0     low
1                0.80                   262                      0  medium
2                0.11                   272                      0  medium
3                0.72                   223                      0     low
4                0.37                   159                      0     low

In [7]:
x['salary'] = x.salary.map({'low' : 0, 'medium' : 1, 'high' : 2})
x['salary']

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0        0
1        1
2        1
3        0
4        0
        ..
14994    0
14995    0
14996    0
14997    0
14998    0
Name: salary, Length: 14999, dtype: int64

In [8]:
x.head()

satisfaction_level  average_montly_hours  promotion_last_5years  salary
0                0.38                   157                      0       0
1                0.80                   262                      0       1
2                0.11                   272                      0       1
3                0.72                   223                      0       0
4                0.37                   159                      0       0

In [9]:
y = data['left']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: left, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 4)

In [11]:
x_train.shape

(11999, 4)

In [12]:
x_test.shape

(3000, 4)

In [13]:
y_train.shape

(11999,)

In [14]:
y_test.shape

(3000,)

In [15]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression(solver = 'lbfgs', C = 0.001)
regr.fit(x_train, y_train)

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
y_test.head()

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [17]:
y_pred = regr.predict(x_test)
y_pred[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [18]:
y_pred_proba = regr.predict_proba(x_test)
y_pred_proba

array([[0.80545189, 0.19454811],
       [0.71678749, 0.28321251],
       [0.78626944, 0.21373056],
       ...,
       [0.73831958, 0.26168042],
       [0.79860944, 0.20139056],
       [0.80365461, 0.19634539]])

In [19]:
a_1 = regr.score(x_train, y_train)

In [20]:
a_2 = regr.score(x_test, y_test)

In [21]:
a_3 = regr.score(x_test, y_pred)

In [22]:
from sklearn.metrics import jaccard_similarity_score, accuracy_score, log_loss, f1_score, classification_report, confusion_matrix

In [23]:
a_4 = jaccard_similarity_score(y_test, y_pred)

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


In [24]:
a_5 = accuracy_score(y_test, y_pred)

In [25]:
a_6 = log_loss(y_test, y_pred)

In [26]:
a_7 = f1_score(y_test, y_pred)

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      1.00      0.87      2287
           1       0.00      0.00      0.00       713

    accuracy                           0.76      3000
   macro avg       0.38      0.50      0.43      3000
weighted avg       0.58      0.76      0.66      3000



c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors = 1)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [29]:
b_1 = knn.score(x_train, y_train)

In [30]:
b_2 = knn.score(x_test, y_test)

In [31]:
y_test.head()

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [32]:
yhat = knn.predict(x_test)
yhat[0:5]

array([0, 1, 0, 0, 1], dtype=int64)

In [33]:
b_3 = knn.score(x_test, y_pred)

In [34]:
b_4 = jaccard_similarity_score(y_test, yhat)

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


In [35]:
b_5 = accuracy_score(y_test, yhat)

In [36]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.96      0.95      0.95      2287
           1       0.84      0.86      0.85       713

    accuracy                           0.93      3000
   macro avg       0.90      0.90      0.90      3000
weighted avg       0.93      0.93      0.93      3000



In [37]:
b_6 = log_loss(y_test, yhat)

In [38]:
b_7 = f1_score(y_test, yhat)

In [39]:
from sklearn import svm
clf = svm.SVC(kernel = 'rbf', gamma = 'auto')
clf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
y_test.head()

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [41]:
y_pred_1 = clf.predict(x_test)
y_pred_1[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [42]:
c_1 = clf.score(x_train, y_train)

In [43]:
c_2 = clf.score(x_test, y_test)

In [44]:
c_3 = clf.score(x_test, y_pred_1)

In [45]:
c_4 = jaccard_similarity_score(y_test, y_pred_1)

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


In [46]:
c_5 = accuracy_score(y_test, y_pred_1)

In [47]:
c_7 = f1_score(y_test, y_pred_1)

In [48]:
print(classification_report(y_test, y_pred_1))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      2287
           1       0.78      0.55      0.64       713

    accuracy                           0.86      3000
   macro avg       0.82      0.75      0.78      3000
weighted avg       0.85      0.86      0.85      3000



In [49]:
c_6 = log_loss(y_test, y_pred_1)

In [50]:
from sklearn import tree
clf_1 = tree.DecisionTreeClassifier()
clf_1.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [51]:
y_test.head()

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [52]:
yhat_1 = clf_1.predict(x_test)
yhat_1[0:5]

array([0, 1, 0, 0, 1], dtype=int64)

In [53]:
d_1 = clf_1.score(x_train, y_train)

In [54]:
d_2 = clf_1.score(x_test, y_test)

In [55]:
d_3 = clf_1.score(x_test, y_pred)

In [56]:
print(classification_report(y_test, yhat_1))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      2287
           1       0.87      0.86      0.86       713

    accuracy                           0.94      3000
   macro avg       0.91      0.91      0.91      3000
weighted avg       0.94      0.94      0.94      3000



In [57]:
d_7 = f1_score(y_test, yhat_1)

In [58]:
d_6 = log_loss(y_test, yhat_1)

In [59]:
d_5 = accuracy_score(y_test, yhat_1)

In [60]:
d_4 = jaccard_similarity_score(y_test, yhat_1)

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


In [62]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000)
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [64]:
y_test[0:5]

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [66]:
y_pred_2 = rf.predict(x_test)
y_pred_2[0:5]

array([0, 1, 0, 0, 1], dtype=int64)

In [67]:
e_1 = rf.score(x_train, y_train)
e_1

0.9800816734727894

In [68]:
e_2 = rf.score(x_test, y_test)
e_2

0.9483333333333334

In [69]:
e_3 = rf.score(x_test, y_pred_2)
e_3

1.0

In [70]:
e_4 = jaccard_similarity_score(y_test, y_pred_2)
e_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9483333333333334

In [71]:
e_5 = accuracy_score(y_test, y_pred_2)
e_5

0.9483333333333334

In [72]:
e_6 = log_loss(y_test, y_pred_2)
e_6

1.7845234370061411

In [73]:
e_7 = f1_score(y_test, y_pred_2)
e_7

0.8909218859957775

In [74]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
gsn = GaussianNB()
gsn.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [75]:
y_test[0:5]

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [76]:
yhat_2 = gsn.predict(x_test)
yhat_2[0:5]

array([0, 1, 0, 0, 0], dtype=int64)

In [77]:
f_1 = gsn.score(x_train, y_train)
f_1

0.795316276356363

In [78]:
f_2 = gsn.score(x_test, y_test)
f_2

0.8003333333333333

In [79]:
f_3 = gsn.score(x_test, yhat_2)
f_3

1.0

In [81]:
f_4 = jaccard_similarity_score(y_test, yhat_2)
f_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.8003333333333333

In [82]:
f_5 = accuracy_score(y_test, yhat_2)
f_5

0.8003333333333333

In [83]:
f_6 = log_loss(y_test, yhat_2)
f_6

6.896318048740559

In [84]:
f_7 = f1_score(y_test, yhat_2)
f_7

0.5706093189964159

In [85]:
mul = MultinomialNB()
mul.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [86]:
y_test[0:5]

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [88]:
y_pred_3 = mul.predict(x_test)
y_pred_3[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [89]:
g_1 = mul.score(x_train, y_train)
g_1

0.7618134844570381

In [90]:
g_2 = mul.score(x_test, y_test)
g_2

0.7623333333333333

In [91]:
g_3 = mul.score(x_test, y_pred_3)
g_3

1.0

In [92]:
g_4 = jaccard_similarity_score(y_test, y_pred_3)
g_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.7623333333333333

In [93]:
g_5 = accuracy_score(y_test, y_pred_3)
g_5

0.7623333333333333

In [94]:
g_6 = log_loss(y_test, y_pred_3)
g_6

8.208715856523773

In [95]:
g_7 = f1_score(y_test, y_pred_3)
g_7

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

In [96]:
ber = BernoulliNB()
ber.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [97]:
y_test[0:5]

10669    0
12621    1
13074    0
2764     0
279      1
Name: left, dtype: int64

In [98]:
yhat_3 = ber.predict(x_test)
yhat_3[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [99]:
h_1 = ber.score(x_train, y_train)
h_1

0.7618134844570381

In [100]:
h_2 = ber.score(x_test, y_test)
h_2

0.7623333333333333

In [101]:
h_3 = ber.score(x_test, yhat_3)
h_3

1.0

In [102]:
h_4 = jaccard_similarity_score(y_test, yhat_3)
h_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.7623333333333333

In [103]:
h_5 = accuracy_score(y_test, yhat_3)
h_5

0.7623333333333333

In [104]:
h_6 = log_loss(y_test, yhat_3)
h_6

8.208715856523773

In [105]:
h_7 = f1_score(y_test, yhat_3)
h_7

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

In [106]:
df = pd.DataFrame({'Train_score' : [a_1, b_1, c_1, d_1, e_1, f_1, g_1, h_1],
                  'Test_Score' : [a_2, b_2, c_2, d_2, e_2, f_2, g_2, h_2],
                  'Predicted_Score' : [a_3, b_3, c_3, d_3, e_3, f_3, g_3, h_3],
                  'Jaccard_Similarity_Score' : [a_4, b_4, c_4, d_4, e_4, f_4, g_4, h_4],
                  'accuracy_score' : [a_5, b_5, c_5, d_5, e_5, f_5, g_5, h_5],
                  'log_loss' : [a_6, b_6, c_6, d_6, e_6, f_6, g_6, h_6],
                  'f1_score' : [a_7, b_7, c_7, d_7, e_7, f_7, g_7, h_7]}, index = ['Logistic_Regression', 'KNN', 'SVM', 'Decision_Tree', 'Random_Forest', 'GaussianNB', 'MultinomialNB', 'BernoulliNB'])
df

Train_score  Test_Score  Predicted_Score  \
Logistic_Regression     0.761813    0.762333         1.000000   
KNN                     0.975248    0.927000         0.754667   
SVM                     0.858322    0.855333         1.000000   
Decision_Tree           0.980082    0.935667         0.763333   
Random_Forest           0.980082    0.948333         1.000000   
GaussianNB              0.795316    0.800333         1.000000   
MultinomialNB           0.761813    0.762333         1.000000   
BernoulliNB             0.761813    0.762333         1.000000   

                     Jaccard_Similarity_Score  accuracy_score  log_loss  \
Logistic_Regression                  0.762333        0.762333  8.208716   
KNN                                  0.927000        0.927000  2.521363   
SVM                                  0.855333        0.855333  4.996640   
Decision_Tree                        0.935667        0.935667  2.222020   
Random_Forest                        0.948333        0.948333  1.784523   
GaussianNB                           0.800333        0.800333  6.896318   
MultinomialNB                        0.762333        0.762333  8.208716   
BernoulliNB                          0.762333        0.762333  8.208716   

                     f1_score  
Logistic_Regression  0.000000  
KNN                  0.848861  
SVM                  0.643678  
Decision_Tree        0.864371  
Random_Forest        0.890922  
GaussianNB           0.570609  
MultinomialNB        0.000000  
BernoulliNB          0.000000